### PR TITLE
Added Rspec! 

### PR DESCRIPTION
**Pull request by tylerpendleton**
We are almost ready to go.

### CODE REVIEW

**Comment by tylerpendleton** [comment]
I added the placeholder homepage to this pull request as well as rspec and capybara

**Comment by edwardheming** [comment]
Looks great. Let's setup a time to review how to do tests in rspec since you have a good familiarity. Perhaps we'll have some time at our Sunday meeting?

**Comment by tylerpendleton** [comment]
Sounds good! I'm adding a resources section to our trello board with some cards linking to rspec and capybara lessons and tips

**Comment by bstolte** [comment]
Thumbs up!  Looks good.

**Pull request merged**
