### PR TITLE
added the dashboard, added some authentication

### PR DESCRIPTION
**Pull request by bstolte**
- Added the Current Games dashboard.  
- Added authentication to the page.  
- Adjusted the way games are created to associate a player to game.

### CODE REVIEW

**Comment by tylerpendleton** [comment]
It might make sense to generate the devise player controller and create a def show method there.  The dashboard_controller could be confusing. 

Also, the current_games button from a user perspective looks like it should show all games that are currently being played by everyone, as well as a list of open games that they could join.  From there we could let anyone view that page, but have to sign in to join a game.  Adding an index method to the games_controller to display all games would make more sense for that link.  A  user dashboard link on the right side of the navbar that only showed up if a user was signed in would be less confusing.

I think that these changes will make the app more open to changes and improvements as we move forward.

**Comment by tylerpendleton** [comment]
The current games button with the list of games and open games is a stretch goal and I can handle that part, but the change to the devise controller and user dashboard link would make sense before we merge this over.

**Comment by tylerpendleton** [comment]
Hey guys! Awesome stuff.

From a user perspective it seems like the current games button should link to all the current games being played by everyone, as well as a list of games they could join.

For the user dashboard maybe it should be pulled to the right of the navbar and only show up when a user is logged in

**Comment by tylerpendleton** [comment]
I made those minor tweaks and pushed it back up, check it out!

**Comment by edwardheming** [comment]
I added the current games index page per your suggestion.

**Pull request merged**
