### PR TITLE
added styling for navbar and login

### PR DESCRIPTION
**Pull request by bstolte**
Edward and I added some styling for the navbar and the sign up and login pages.

### CODE REVIEW

**Comment by tylerpendleton** [comment]
This looks great to me.  Do we want to go with a dark theme for the navbar like in the wireframes?

**Comment by bstolte** [comment]
Yep.  We ran into an issue with the putting the dark theme into the app.
Since we only had about an hour, we moved forward with styling the login /
sign up views and put in a navbar for the links.  Still want to add the
theme.

**Comment by bstolte** [comment]
Added styling to the "Forgot password" view, logout link logic for the navbar.

**Comment by edwardheming** [comment]
Added dark theme to nav bar and hero page. Updated devise views for consistency.

**Pull request merged**
