### PR TITLE
added data models for game and piece

### PR DESCRIPTION
**Pull request by bstolte**
added the data models for games and pieces.  players will be done after we add the devise gem.  we also add some associations.

### CODE REVIEW

**Comment by gruzzlymug** [comment]
Suppose you have a Game object...how will you determine who is player 1 (white) and who is player 2 (black)?

**Comment by gruzzlymug** [comment]
Think about how you will get all of the pieces for a particular player in a Game.

**Comment by edwardheming** [comment]
I think the way we would want to do that is that whichever player starts a game first would be assigned a player_color at that time for that particular game.

**Comment by gruzzlymug** [comment]
I meant something slightly different. Suppose you have a Game object called game, how would you get the players out of it?
```
game = Game.new
# do some stuff to initialize the game
# finish this code:
p1 = game.<some way to get the white player>
p2 = game.<some way to get the black player>
```

**Comment by edwardheming** [comment]
Once Gretchen adds Devise (which will add the Player model) we will modify the existing Game migration to include an add_index for the :player_id from the Player model.

**Pull request merged**
