### PR TITLE
Added jQuery function to allow selection of all pieces.

### PR DESCRIPTION
**Pull request by edwardheming**
Added jQuery function to allow selection of all pieces. One issue we ran into was that <td> does not have a specific piece id. So selecting a specific piece will require that we add this information to the board model.

### CODE REVIEW

**Comment by gruzzlymug** [comment]
jQuery is a great way to do this. It's going to affect the way you redraw the board, potentially.

I'd recommend updating the variable names to reflect what the code is meant to do. It looks like you have pasted some generic example code there.

**Comment by gruzzlymug** [comment]
Also, you probably want to read up on how jQuery is integrated into rails. You've included the script link but jQuery comes installed in rails apps, so you don't need that. See these files:
https://github.com/Team-whip/chess_app/blob/master/Gemfile#L18
https://github.com/Team-whip/chess_app/blob/master/app/assets/javascripts/application.js#L13

I'd start with the official doc, it's brief and covers rails integration (that's already done by default, just read this for some understanding), and then look for other resources for using it in the app.
https://github.com/rails/jquery-rails

**Comment by edwardheming** [comment]
Updated variable names and removed extra jQuery loading script.

**Comment by edwardheming** [comment]
I've updated the jQuery function to show an alert when you select the "td" html. We still need to identify a specific piece but this gets us a bit further.

**Pull request merged**
